import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { AudioShell, images, Nav, Newsletter, PullQuote, textures } from '@/components/editorial';

const rankData = [
  ['1','GROUNDWORK.BLR','Bangalore','Hand-cut leather inlay work that treats the shoe like a canvas for actual Bangalore street-map geography — literally embedding local landmarks into the design. Nobody else is doing site-specific storytelling at this level.'],
  ['2','RESIN.RAJA','Hyderabad','A signature look built around hand-poured resin detailing on outsoles — glossy, almost jewelry-like finishing that has become instantly recognizable.'],
  ['3','FLIPSIDE STUDIOS','Mumbai','Deconstructs retail sneakers entirely and rebuilds them with mismatched panel work. Genuinely unpredictable, every piece looks different.'],
  ['4','INKWELL DELHI','Delhi','Hand-painted portraiture on canvas sneakers, heavy on Delhi street-art influence. Technical painting skill is arguably the best here.'],
  ['5','TAPE & TONE','Bangalore','Airbrush gradient specialist with a disciplined colour theory approach. Every piece looks like it belongs to the same collection.'],
  ['6','SOLE SUTRA','Pune','Hand-embroidery on canvas uppers, pulling from regional textile patterns. Deeply original and culturally specific.'],
  ['7','UNDERGROUND UPCYCLE','Chennai','Builds from reclaimed materials — old jerseys, scrap denim, discarded leather. Rough-edged and distinct.'],
  ['8','LACEWORK LDN-BOM','Mumbai','Custom lace and hardware swaps with subtle sole painting. Smaller interventions, reliably clean.'],
  ['9','STREET SUTURE','Delhi','Visible-stitch “repair as design” work — deliberately exposed thread that turns damage into the feature.'],
  ['10','STUDIO KHADDAR','Hyderabad','Hand-dyed fabric overlays inspired by khadi textures. Newest name here, building on originality and early resonance.'],
];

function Piece({ id, label, title, subhead, image, children }: { id:string; label:string; title:string; subhead:string; image?:string; children:ReactNode }) {
  return <section className="piece" id={id}><div className="piece-label">{label}</div><div><h2>{title}</h2><p className="subhead">{subhead}</p>{image && <img className="piece-image" src={image} alt="" />}{children}</div><div className="piece-aside mono" style={{fontSize:10,color:'#766c60',textTransform:'uppercase',writingMode:'vertical-rl'}}>Undersole / Field notes</div></section>;
}
function Para({ children }: { children: ReactNode }) { return <p>{children}</p>; }
function Disclosure({ children }: { children: ReactNode }) { return <div className="disclosure">AI DISCLOSURE: {children}</div>; }

export default function IssuePage() {
  const [filter, setFilter] = useState('all');
  const [scroll, setScroll] = useState(0);
  useEffect(() => { const fn = () => { const max = document.documentElement.scrollHeight - window.innerHeight; const ratio = max > 0 ? window.scrollY / max : 0; setScroll(ratio); const bar = document.getElementById('reading-progress'); if (bar) bar.style.transform = `scaleX(${ratio})`; }; window.addEventListener('scroll', fn, {passive:true}); fn(); return () => window.removeEventListener('scroll', fn); }, []);
  const ranks = useMemo(() => filter === 'all' ? rankData : rankData.filter(row => row[2] === filter), [filter]);
  const locations = ['all', ...Array.from(new Set(rankData.map(row => row[2])))];
  return <div className="page-in"><div className="grain" style={{backgroundImage:`url(${textures.masthead})`}} /><Nav reader />
    <main>
      <header className="reader-hero"><div className="kicker">Undersole / Issue 01 / The access issue</div><h1>Everything<br />underfoot<span className="orange">.</span></h1><p>Five dispatches from the Indian sneaker underground — where scarcity becomes currency, custom becomes craft, and cricket gets a fit check.</p></header>
      <article className="reader">
        <Piece id="piece-1" label="01 / Deep-dive" title="The rise of India's sneaker resale economy" subhead="Words / Undersole editorial desk" image={images.resale}>
          <div className="piece-body"><Para>It's 11:47 PM on a Thursday and a WhatsApp group called “DELHI COP SQUAD” has forty-three unread messages. Somewhere in there, a pair of size 9 Jordans that retailed for ₹8,995 four hours ago just sold for ₹19,000 to a stranger who will pick them up outside a metro station tomorrow, cash only, no questions about the box condition.</Para><Para>Nobody in this group has met in person. Nobody needs to. This is how sneakers move in India now — not through stores, but through group chats that function like unlicensed stock exchanges, where the product is scarcity itself.</Para><PullQuote>Not leather and rubber. Timing.</PullQuote><Para>India’s official sneaker supply is thin and the demand curve got steep fast. Global drops land here in smaller allocations than in the US or Europe, if they land at all. Add import duty, add a brand's habit of pricing limited releases well above what most buyers can justify, and you get a market where the person who's fastest — not richest, fastest — walks away with product that's worth more the second they own it.</Para><Para>That gap between retail and “the second after” is where the entire resale economy lives. On one hand, this is legitimate hustle. On the other, every successful flip means someone who actually wanted to wear the shoes got priced out. The resale guy isn't the villain of this story, exactly — but he's not neutral either.</Para><Para>If supply loosens even slightly, the ₹8,000-to-₹18,000 math stops working. A lot of “resale businesses” that look like hustle right now are going to look like a bubble in hindsight.</Para><Disclosure>This piece was drafted with AI assistance and edited/directed by Undersole's editorial team. Text: AI-drafted, human-edited and fact-checked.</Disclosure></div>
        </Piece>
        <Piece id="piece-2" label="02 / Review" title={'Air Jordan 1 “Lost & Found”'} subhead="Is it worth the hype in India?" image={images.aj1}>
          <div className="piece-body"><Para>Let's get the obvious out of the way: the “Lost & Found” colorway was never really about the shoe. It was about the story — the whole aged, “left in a warehouse for 25 years” premise Jordan Brand built the release around. Cute marketing. It doesn't tell you whether the shoe holds up on Indian streets, in Indian heat, at Indian resale prices.</Para><Para><strong>First impressions:</strong> The yellowed midsole and deliberately unfinished swoosh stitching look genuinely great in person. It doesn't read as distressed for the sake of it. There's real restraint in the design.</Para><Para><strong>Build quality:</strong> Solid, unsurprising for a Jordan 1 — full-grain leather upper that breaks in fast, decent ankle support if you're actually going to move in these.</Para><Para><strong>Local pricing reality:</strong> Retail landed around ₹16,000–17,000. Resale has sat north of ₹25,000–28,000 for clean pairs. That is a steep premium for a shoe whose main selling point is looking intentionally old.</Para><Para><strong>The actual verdict:</strong> At retail, cop it without overthinking. At resale prices north of ₹25K, this is a “want” purchase, not a “worth it” purchase. Worth the hype? Sure. Worth the markup? Only if the story is doing something for you that the shoe alone isn't.</Para><Disclosure>This piece was drafted with AI assistance and edited/directed by Undersole's editorial team. Pricing figures are illustrative market estimates for editorial purposes, not verified real-time listings.</Disclosure></div>
        </Piece>
        <Piece id="piece-3" label="03 / Ranking" title="Top 10 Indian sneaker customizers right now" subhead="A field ranking, not a follower count" image={images.customizer}>
          <div className="piece-body"><Para><strong>Methodology:</strong> originality of technique, consistency of output, cultural relevance and local storytelling, and community reputation among people who actually commission custom work. Follower count is explicitly not a factor.</Para></div>
          <div className="ranking-tools">{locations.map(location => <button key={location} className={`rank-filter ${filter === location ? 'active' : ''}`} onClick={() => setFilter(location)} data-testid={`button-filter-${location.toLowerCase().replace(' ','-')}`}>{location}</button>)}</div>
          <div className="rank-list">{ranks.map(row => <div className="rank-row" key={row[1]} data-testid={`row-customizer-${row[0]}`}><div className="rank-number">{row[0]}</div><div><h3>{row[1]} <span style={{color:'#8d8173',fontSize:11,fontFamily:'DM Mono'}}>/ {row[2]}</span></h3><p>{row[3]}</p></div></div>)}</div>
          <Disclosure>This ranking features illustrative scene archetypes created for editorial purposes — composite/fictional customizer profiles representing real techniques and trends visible in India's customization scene, not verified real individuals or businesses.</Disclosure>
        </Piece>
        <Piece id="piece-4" label="04 / Trend analysis" title="Cricket culture meets sneaker culture" subhead="The new wave" image={images.cricket}>
          <div className="piece-body"><Para>Walk into any street cricket match in urban India right now and the fit-check has quietly changed. It's not whites-and-boots anymore: it's a bowler warming up in resole-worn Jordan 1s, a batter between overs in a jersey knotted at the waist over joggers and a pair of clean AF1s.</Para><Para>This isn't sneakers invading cricket. It's cricket culture — with its team colours, player numbers and jersey silhouettes — finally colliding with a streetwear scene hungry for something distinctly Indian to build around instead of importing American hype-drop culture wholesale.</Para><Para>Stadium culture is where this is most visible. Coordinated jersey-and-sneaker match-day fits are becoming their own subgenre. You can't fake being from a specific fan base the way you can fake liking a global shoe brand.</Para><PullQuote>The next evolution isn't more crossover content — it's official collaboration.</PullQuote><Para>Expect the first real IPL-team-branded sneaker capsule within the next two seasons, and expect resale to treat it like a religious event.</Para><Disclosure>This piece was drafted with AI assistance and edited/directed by Undersole's editorial team. Text: AI-drafted, human-edited and fact-checked.</Disclosure></div>
        </Piece>
        <Piece id="piece-5" label="05 / Simulated interview" title="Rehan, underground customizer" subhead="22 / Hyderabad / Self-taught" image={images.rehan}>
          <AudioShell /><div className="piece-body"><Para><strong>Undersole: How did you start customizing?</strong></Para><Para>Rehan: Honestly, by accident. I ruined my first pair trying to fix a scuff — used the wrong kind of nail polish, thought I was being clever, and it bled into this weird cloudy pattern across the toe box. A friend saw them and asked where I bought “those”. That messed with my head a little. Made me realize the mistake looked more interesting than the shoe did before I touched it.</Para><Para><strong>Undersole: Why turn down the corporate collabs?</strong></Para><Para>Rehan: Because what they actually wanted was my name attached to their design decisions. One sent a moodboard already approved by three people. My job was to execute someone else's idea. The moment somebody else is picking the colours, it's not mine anymore. I'd rather sell twenty pairs that are actually mine than ten thousand pairs I just signed off on.</Para><Para><strong>Undersole: What's hardest about doing this in India?</strong></Para><Para>Rehan: Materials. Half the resin, pigments and adhesives, I'm importing myself or hunting through specific markets because there’s no real customizer supply store here. You learn to substitute. It slows everything down.</Para><Para><strong>Undersole: What's next?</strong></Para><Para>Rehan: I'm trying to get some materials made locally. If that works, this stops being a bedroom hustle and starts looking like a sustainable practice. The goal is not to blow up. Just to not depend on getting lucky with an import shipment.</Para><Disclosure>This is a simulated interview with a composite/fictional persona representing real perspectives and working conditions observed in India's underground sneaker customization scene. “Rehan” is not a real named individual.</Disclosure></div>
        </Piece>
      </article>
      <div style={{padding:'0 18px 110px',maxWidth:1136,margin:'0 auto'}}><Newsletter /></div>
    </main>
    <footer className="footer"><span>Issue 01 / End of transmission</span><span>Undersole — India</span><span style={{color:'#ff5c16'}}>{Math.round(scroll * 100)}% read</span></footer>
  </div>;
}